# Generated by Django 2.1.3 on 2019-04-30 04:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Python', max_length=500)),
                ('image', models.FileField(blank=True, upload_to='syllabus/static/syllabus/site-data/course-pictures')),
                ('description', models.TextField(default='Lorem ipsum')),
                ('start_time', models.DateTimeField(default=datetime.datetime.now)),
                ('end_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(default='https://incwellventure.com', max_length=500)),
                ('link_for', models.CharField(default='Github', max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='link',
            field=models.ManyToManyField(related_name='course_links', to='syllabus.Link'),
        ),
    ]
