# Generated by Django 2.1.3 on 2019-04-30 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='end_time',
            new_name='endTime',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='start_time',
            new_name='startTime',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='link_for',
            new_name='linkFor',
        ),
    ]
