# Generated by Django 2.1.3 on 2019-04-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Incwell Technology', max_length=99)),
                ('work1', models.IntegerField(default='5200000')),
                ('work2', models.IntegerField(blank=True, null=True)),
                ('mobile1', models.IntegerField(default='5200000')),
                ('mobile2', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(default='Arun thapa Chowk', max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Us', max_length=300)),
                ('image', models.FileField(blank=True, upload_to='bootcamp/static/bootcamp/site-data/content-pictures')),
                ('description', models.TextField(default='Lorem ipsum')),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='John', max_length=300)),
                ('last_name', models.CharField(default='Doe', max_length=300)),
                ('photo', models.FileField(blank=True, upload_to='bootcamp/static/bootcamp/site-data/profile-pictures')),
                ('designation', models.CharField(default='Software Engineer', max_length=300)),
                ('summary', models.TextField(default='Lorem ipsum')),
                ('facebookLink', models.CharField(default='https://fb.com', max_length=800)),
                ('mediumLink', models.CharField(default='https://medium.com', max_length=800)),
                ('twitterLink', models.CharField(default='https://twitter.com', max_length=800)),
                ('githubLink', models.CharField(default='https://github.com', max_length=800)),
                ('linkedinLink', models.CharField(default='https://linkedin.com', max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(default='DevOps', max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='mentor',
            name='skill',
            field=models.ManyToManyField(related_name='mentor_skills', to='bootcamp.Skill'),
        ),
    ]
