# Generated by Django 2.1.3 on 2019-04-30 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='facebookLink',
            new_name='facebookUsername',
        ),
        migrations.RenameField(
            model_name='mentor',
            old_name='githubLink',
            new_name='githubUsername',
        ),
        migrations.RenameField(
            model_name='mentor',
            old_name='linkedinLink',
            new_name='linkedinUsername',
        ),
        migrations.RenameField(
            model_name='mentor',
            old_name='mediumLink',
            new_name='mediumUsername',
        ),
        migrations.RenameField(
            model_name='mentor',
            old_name='twitterLink',
            new_name='twitterUsername',
        ),
    ]
