# Generated by Django 2.1.3 on 2019-04-30 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamp', '0002_auto_20190430_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='facebookUsername',
            field=models.CharField(default='username', max_length=800),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='githubUsername',
            field=models.CharField(default='username', max_length=800),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='linkedinUsername',
            field=models.CharField(default='username', max_length=800),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='mediumUsername',
            field=models.CharField(default='username', max_length=800),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='twitterUsername',
            field=models.CharField(default='username', max_length=800),
        ),
    ]
