# Generated by Django 2.1.3 on 2019-04-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamp', '0004_auto_20190430_0643'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Mobile', max_length=300)),
                ('phone', models.IntegerField(default='98000000')),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='mobile1',
        ),
        migrations.RemoveField(
            model_name='company',
            name='mobile2',
        ),
        migrations.RemoveField(
            model_name='company',
            name='work1',
        ),
        migrations.RemoveField(
            model_name='company',
            name='work2',
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.ManyToManyField(related_name='company_phone', to='bootcamp.PhoneNumber'),
        ),
    ]
