# Generated by Django 2.1.3 on 2019-06-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('syllabus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=800)),
                ('projectLink', models.CharField(max_length=300)),
                ('planToContribute', models.TextField()),
                ('education', models.CharField(max_length=500)),
                ('university', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=200)),
                ('fullName', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='StudentEnroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=400)),
                ('email', models.CharField(max_length=600)),
                ('gender', models.BooleanField(choices=[(True, 'Male'), (False, 'Female')], max_length=1)),
                ('education', models.CharField(max_length=800)),
                ('phone', models.CharField(max_length=500)),
                ('gitLink', models.CharField(blank=True, max_length=800, null=True)),
                ('firstName', models.CharField(max_length=300)),
                ('middleName', models.CharField(blank=True, max_length=300, null=True)),
                ('lastName', models.CharField(max_length=300)),
                ('course', models.ManyToManyField(related_name='student_course', to='syllabus.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Talk_To_Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=70)),
                ('skypeId', models.CharField(max_length=300)),
            ],
        ),
    ]
