# Generated by Django 2.1.3 on 2019-04-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='John', max_length=300)),
                ('middle_name', models.CharField(blank=True, max_length=300, null=True)),
                ('last_name', models.CharField(default='Doe', max_length=300)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('gender', models.BooleanField(default=True)),
                ('education', models.CharField(default='Incwell Bootcamp', max_length=800)),
                ('phone', models.CharField(default='9800000', max_length=500)),
                ('git_link', models.CharField(blank=True, default='No Git link', max_length=800, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Talk_To_Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='John', max_length=300)),
                ('last_name', models.CharField(default='Doe', max_length=300)),
                ('email', models.EmailField(default='noemail@email.com', max_length=70)),
            ],
        ),
    ]
