# Generated by Django 2.1.3 on 2019-05-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0001_initial'),
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enroll',
            name='course',
        ),
        migrations.AddField(
            model_name='enroll',
            name='course',
            field=models.ManyToManyField(related_name='enroll_course', to='syllabus.Course'),
        ),
        migrations.RemoveField(
            model_name='enroll',
            name='student',
        ),
        migrations.AddField(
            model_name='enroll',
            name='student',
            field=models.ManyToManyField(related_name='enroll_student', to='visitor.Student'),
        ),
    ]
