# Generated by Django 2.1.3 on 2019-04-30 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enroll',
            old_name='git_link',
            new_name='gitLink',
        ),
    ]
