# Generated by Django 2.1.3 on 2019-04-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0002_auto_20190430_0643'),
        ('visitor', '0002_auto_20190430_0509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='John', max_length=300)),
                ('middleName', models.CharField(blank=True, max_length=300, null=True)),
                ('lastName', models.CharField(default='Doe', max_length=300)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('gender', models.BooleanField(default=True)),
                ('education', models.CharField(default='Incwell Bootcamp', max_length=800)),
                ('phone', models.CharField(default='9800000', max_length=500)),
                ('gitLink', models.CharField(blank=True, default='No Git link', max_length=800, null=True)),
                ('course', models.ManyToManyField(related_name='student_course', to='syllabus.Course')),
            ],
        ),
        migrations.RenameField(
            model_name='talk_to_mentor',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='talk_to_mentor',
            old_name='last_name',
            new_name='lastName',
        ),
        migrations.RemoveField(
            model_name='enroll',
            name='education',
        ),
        migrations.RemoveField(
            model_name='enroll',
            name='email',
        ),
        migrations.RemoveField(
            model_name='enroll',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='enroll',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='enroll',
            name='gitLink',
        ),
        migrations.RemoveField(
            model_name='enroll',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='enroll',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='enroll',
            name='phone',
        ),
        migrations.AddField(
            model_name='enroll',
            name='course',
            field=models.ManyToManyField(related_name='enroll_course', to='syllabus.Course'),
        ),
        migrations.AddField(
            model_name='enroll',
            name='student',
            field=models.ManyToManyField(related_name='enroll_student', to='visitor.Student'),
        ),
    ]
