# Generated by Django 2.1.3 on 2019-05-01 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0003_auto_20190430_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.BooleanField(choices=[(True, 'Publish'), (False, 'Unpublished')], default=True, max_length=1),
        ),
    ]
